# Generated by Django 3.0 on 2022-04-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='my_new_app.StudentHomework', verbose_name='Домашка'),
        ),
    ]
