# Generated by Django 3.0 on 2022-02-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_new_app', '0002_group_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='Полное имя')),
                ('topic', models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('golang', 'Golang'), ('typescript', 'Typescript'), ('swift', 'Swift'), ('php', 'PHP'), ('matlab', 'MatLab'), ('sql', 'SQL'), ('ruby', 'Ruby'), ('delphi', 'Delphi')], default='java', max_length=30, verbose_name='Предмет')),
                ('students', models.ManyToManyField(to='my_new_app.Student')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ('full_name',),
            },
        ),
    ]
